### ISSUE TITLE
Skip SMS auth when TOTP is enabled

### ISSUE THREAD

**Issue by reefdog** [PhilanthropyDataCommons/auth#19]
So it seems that you can setup your Keycloak account to use TOTP (google authenticator, etc.) from [the account management page](https://auth.philanthropydatacommons.org/realms/pdc/account/#/security/signingin). Neat! However, the login UX after you've done so still requires SMS. It just inserts the TOTP code entry between username/password and SMS.

Can we configure Keycloak so that a user who enables TOTP doesn't need to use SMS any more?

(TOTP is substantially more secure than SMS, and our defaulting to SMS for broad accessibility shouldn't limit more security-minded users from using TOTP.)

If this is captured by another existing issue, please feel free to close.

**Comment by jasonaowen** [comment]
Note that in addition to the technical question of "can we do it?", there is also the business question of "should we?". The original requirement, as I understood it, was that everyone must use SMS MFA. I don't have the context of who imposed that requirement or what their motivation for doing so was, but we should persuade them that TOTP is a better alternative: less expensive, more secure, and better supported by Keycloak.

**Comment by reefdog** [comment]
I believe the requirement was:

1. We must use MFA, and
2. We must support SMS

I don't think ② was meant to limit _users_ to SMS as the maximum secure method, but to limit _us_ from requiring anything less universally-available.

I'd be on board any effort to raise our minimum required security from SMS to TOTP, but I think that requires a larger stakeholder discussion than letting users opt-in to a higher level of security. The scope of this particular issue is meant to be: can we disable the SMS requirement for those users who self-discover Keycloak's TOTP support?

**Comment by jasonaowen** [comment]
That's a more granular - and promising - breakdown of the requirement than I had understood! Thanks, @reefdog. +1 to everything else - I didn't mean to suggest that we should require TOTP, just making sure that setting up that alternative would be acceptable.

**Comment by jasonaowen** [comment]
As an aside, a pattern I have seen elsewhere and liked was giving the user the option of which factor they want to use at login time: TOTP, SMS, WebAuthn, etc. I don't know if Keycloak supports that flexibility, or what we'd need to do with our SMS plugin to opt into that if it does.

**Comment by reefdog** [comment]
Agreed, I think that's preferable! Though even that level of user complication will probably raise a round of stakeholder conversations, while I think OTS — or at least a smaller part of the pilot leadership — can unilaterally decide to disable-SMS-if-TOTP-self-enrolled.

**Comment by reefdog** [comment]
@kfogel, in Zulip:

> MacFound IT just requires that each PDC user use MFA of some kind; then layered over that baseline institutional requirement, the PDC team (especially John Mohr and Liz Kane of MacFound) decided that the PDC must offer SMS as an MFA method. However, if we wanted to offer other methods, such as authenticator app for those users who prefer that, that would be fine -- the PDC team has no objection to that, it's just an issue of cost (i.e., how much more development time to support another MFA method) and really is our call.
>
> So there is no requirement that users use SMS in particular. Rather, the requirements are: the PDC shall require MFA, and the PDC shall offer SMS as an MFA method. If we choose to offer other MFA methods, that's fine too (but we don't have to, in which case we would effectively be requiring that users use SMS as their second factor, of course).

@jim-mcgowan:

> Agreed.

**Comment by bickelj** [comment]
This should be configurable within Keycloak in the flow selected for "Browser", I hope.

**Comment by bickelj** [comment]
I'm using the guide at https://www.keycloak.org/docs/23.0.7/server_admin/#_authentication-flows to experiment in test. My current thought is to start with the way this issue describes it and then perhaps let either SMS or TOTP be chosen on each and every login. This is obviously less desirable than #31 which is a next step after that.

**Comment by bickelj** [comment]
Using this flow is an improvement that I think is in line with this issue:

![Potential new auth flow](https://github.com/PhilanthropyDataCommons/auth/assets/8806433/29f31cb2-d4ef-4dd4-a53e-16ad632053e6)


If you have not configured TOTP aka an authenticator app, then it will require an SMS code.

If you have configured TOTP, it will first ask for your TOTP code but offer a "Try another way" link.

![TOTP configured with Try another way available](https://github.com/PhilanthropyDataCommons/auth/assets/8806433/c4c35523-aad4-4c4e-873b-7cbb5c769756)


This link goes to a form that allows you to pick either TOTP or SMS code.

![image](https://github.com/PhilanthropyDataCommons/auth/assets/8806433/198205fa-eb59-4928-ad5e-769c4e96eddf)


If you use TOTP, no SMS code is required. If you use SMS code, no TOTP is required.


The only thing that gives me pause is something in our extension that makes the SMS option name ugly, so I think we should fix that first.

@jmergy @reefdog How does this sound, though?

**Comment by jmergy** [comment]
@bickelj I can test but yes, seems like the way to go here.

**Comment by bickelj** [comment]
Hmm, this should help with the weird SMS auth option display name: https://keycloak.discourse.group/t/kerberos-spnego-display-name-and-help-text/4636

@jmergy I emailed you test account info.

**Comment by jmergy** [comment]
@slifty makes me think we might need to include the SMS service into the version of an application "stack" diagram as well. 
![image](https://github.com/PhilanthropyDataCommons/auth/assets/2380410/fc21041a-83f5-4263-8b77-a53dc933d023)

I'll test @bickelj thanks for the creds.

**Comment by reefdog** [comment]
@bickelj This is a great start!

I think starting with TOTP entry is a good way to nudge people toward that (more secure) option. But instead of "Try another way", are we able to link directly to the SMS authenticator flow and name that link "Use SMS instead"?

I'd also like to add just a little instructional text to that page. Is that configurable through the Keycloak interface (and if so could you point me to where) or do we need to mess with templates?

**Comment by reefdog** [comment]
@bickelj Re-reading my message, "This is a great start" was unintentionally minimizing of this. Better: "This is nearly perfect! Here are a few little things I'd love to sand down…" 😆

**Comment by bickelj** [comment]
@reefdog Nice, yes, thanks! I'm looking into the themes but happy to let you pick this up. I think what we want is a new file `src/main/resources/theme/pdc-keycloak-theme/login/messages/messages_en.properties` in the theme dir with something like this:
```
sms-authenticator-display-name = SMS One Time Passcode
sms-authenticator-help-text = Enter a verification code sent via SMS to your mobile telephone.
```

As for the icon, I think that cell phone icon comes from the default theme here:
```
theme/keycloak/login/theme.properties:kcAuthenticatorOTPClass=fa fa-mobile list-view-pf-icon-lg
theme/keycloak/login/theme.properties:kcLoginOTPListItemIconClass=fa fa-mobile
```

So we also need to figure out what to add to our pdc-keycloak-theme login theme properties to set our SMS app to the clamshell mobile phone (https://emojipedia.org/clamshell-mobile-phone 🖁) using font-awesome.

**Comment by bickelj** [comment]
> @bickelj This is a great start!
> 
> I think starting with TOTP entry is a good way to nudge people toward that (more secure) option. But instead of "Try another way", are we able to link directly to the SMS authenticator flow and name that link "Use SMS instead"?
> 
> I'd also like to add just a little instructional text to that page. Is that configurable through the Keycloak interface (and if so could you point me to where) or do we need to mess with templates?

Short answer is I'm sure it's possible but not sure how difficult it is. The "try another way" came up only with the flow configuration set to have those two alternatives. Likewise the list of options came up with the flow configuration. So there isn't a page somewhere that we had to create.

I know we can require a particular user to configure TOTP on next login. And I know we could require TOTP configuration for all users with the flow. I'm not sure how to nudge folks into that direction yet, e.g. "Set up TOTP, oh by the way, fall back on SMS here."

**Comment by bickelj** [comment]
With the addition of `messages_en.properties` and the two lines in it ([see above](https://github.com/PhilanthropyDataCommons/auth/issues/19#issuecomment-1967884646)) things look better on the "try another way" auto-generated form:

![Try Another Way](https://github.com/PhilanthropyDataCommons/auth/assets/8806433/382bc6ac-dc08-4450-a5e3-226f8ae716c7)


This is using a locally-built jar in the test environment. I started to set up a local Keycloak dev environment and before long concluded it will be faster, easier, and more accurate to try it in our test environment.

@reefdog I suppose the cheapest way to get some messaging in there is in that message, then. Perhaps one of the templates is the "right" place as well. I probably spent too much time trying to figure out how to change that little icon and decided to punt on it. I see there is a CSS class attached to one of the OTP-related classes that is specified in the theme. It wasn't clear how to set the CSS class name to our classes in our SMS Authenticator jar (and that's where I left off).

**Comment by slifty** [comment]
I think it looks great, but also just wanna throw in the idea that I think this issue was very specific in the goal (which was accomplished earlier). Maybe we could make a new issue to capture tweaking this screen and prioritize it?  I'm wary of entering "we fixed X so now we also need to perfect Y" mode.

**Comment by bickelj** [comment]
@reefdog I found evidence that [we can (ab)use CSS to change content](https://www.delftstack.com/howto/css/css-change-content/) e.g. in https://github.com/PhilanthropyDataCommons/auth/blob/main/pdc-keycloak-theme/src/main/resources/theme/pdc-keycloak-theme/login/resources/css/style.css. But I don't think that's the right way. Changing the template and messages would be better.

The trouble comes when trying to test changes to the theme locally. It is easier to test in our test environment but even this is a bit of a pain:
1. Build the new jar `../gradlew jar`
2. Copy the jar to the test machine
3. Move the old jar out of the existing/running keycloak `providers` directory
4. Copy the new jar into the existing/running keycloak `providers`
5. Stop keycloak (`systemctl stop ...`)
6. Run the `kc.sh build` command
7. Start keycloak (`systemcl start ...`)
8. Look at logs for errors (`journalct ...`) and fix as needed
9. Now see the changes in the test environment!

**Comment by bickelj** [comment]
I deployed the improvement to production a couple of minutes ago. Now one can log in with either SMS or TOTP (if configured already) but it does not require both. In order to make this change more user-friendly for actual users, we have additional issues #32 #31 and #34.
