### ISSUE TITLE
Github workflow jobs names aren't descriptive

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/auth#21]
The github workflows we have use names like `target_node` -- these names should reflect the task being performed (e.g. `test` or `build`.  They're used in various interfaces such as the branch protection rules 

<img width="750" alt="image" src="https://user-images.githubusercontent.com/208884/231184479-8d2c0d10-6a6f-4508-a6cd-c0c78b97e7e2.png">

**Comment by slifty** [comment]
This might just be a bug / weirdness with GitHub.  I'm closing this issue.  Next time I set up a project I might spend 15m to see if there are better naming conventions but it isn't worth the time right now!

**Comment by slifty** [comment]
I'm re-opening this after feedback from @jasonaowen -- worth patching at some point (when we have a second!)

**Comment by bickelj** [comment]
@slifty This should be better with the merge of #28, the first commit in that branch. Reopen if this isn't correct.
